# Generated by Django 4.0.5 on 2022-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-10-18'),
            preserve_default=False,
        ),
    ]
